### PR TITLE
startLinearAdMode only triggers adstart from appropriate states

### PR DESCRIPTION
**Pull request by incompl**

### CODE REVIEW

**Comment by gkatsev** [comment]
I wonder if we should add a test for this.
Otherwise, LGTM.

**Comment by incompl** [comment]
@gkatsev Added a test, would like review on that too, not sure it's the most useful test or how else we might test it.

**Comment by misteroneill** [comment]
Just a thought, but I wonder if this ought to be a whitelist instead of a blacklist?

**Comment by gkatsev** [comment]
Isn't this a whitelist? You can only `adstart` from these 3 states?

**Comment by misteroneill** [comment]
Haha, you're right, I read it too fast. Ignore me. Carry on. :laughing:

**Comment by gkatsev** [comment]
LGTM

**Comment by incompl** [comment]
@gkatsev @misteroneill Looks like this is good to go, merge away!

**Pull request merged**
