### PR TITLE
Allow ad impl to skip wait for preroll if it is known there is no preroll coming

### PR DESCRIPTION
**Pull request by incompl**

### CODE REVIEW

**Comment by misteroneill** [comment]
I wonder about the naming, but perhaps more information on the purpose of this would be beneficial?

**Comment by incompl** [comment]
@misteroneill You made me realize this should be in the README. I added it. What do you think?

**Comment by misteroneill** [comment]
Sounds good to me. Would be good to get another set of eyes on this, though.

**Comment by gkatsev** [comment]
LGTM

**Pull request merged**
