### PR TITLE
Fix android timing issues

### PR DESCRIPTION
**Pull request by incompl**
This fixes a couple issues on Android where an ad would not pause the video and/or the content would not resume correctly after the ad.

### CODE REVIEW

**Comment by misteroneill** [comment]
LGTM

**Comment by apesant** [comment]
Hi,

I just noticed that this fix seems to break the getPlayerSnapshot method on iOS. There is an exception being thrown. Could you try it?

**Comment by incompl** [comment]
Thanks for reporting this, @apesant. I've pushed a fix for that issue to this pull request.

**Comment by apesant** [comment]
Thanks, it seems to work now :)
Do you have an ETA about when this will be merged and released? I don't need an exact date, a rough approximation is fine!

**Comment by incompl** [comment]
I'm guessing within the next week or two.

**Comment by pagarwal123** [comment]
Looks good to me now

**Pull request merged**
