### PR TITLE
Fixed typographical error, changed accomodate to accommodate in README.

### PR DESCRIPTION
**Pull request by orthographic-pedant**
@videojs, I've corrected a typographical error in the documentation of the [videojs-contrib-ads](https://github.com/videojs/videojs-contrib-ads) project. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by misteroneill** [comment]
As long as we're being pedantic, that seems like more of a spelling error than a typographic error.

**Comment by thoppe** [comment]
Respectfully I disagree.

> A typographical error (often shortened to typo) is a mistake made in the typing process (such as a spelling mistake)[2] of printed material. Historically, this referred to mistakes in manual type-setting (typography). The term includes errors due to mechanical failure or slips of the hand or finger,[2] but excludes errors of ignorance, such as spelling errors. Before the arrival of printing, the "copyist's mistake" or "scribal error" was the equivalent for manuscripts. Most typos involve simple duplication, omission, transposition, or substitution of a small number of characters.

https://en.wikipedia.org/wiki/Typographical_error

**Comment by misteroneill** [comment]
I guess it comes down to whether or not the mistake was due to mechanical failure or ignorance. I guess we'll never know.

**Comment by thoppe** [comment]
I like to take the optimistic approach and assume the best from people. Additionally this justifies the use of the original phrase.

**Pull request merged**
