### PR TITLE
Feature: isAdLoading public method

### PR DESCRIPTION
**Pull request by mysuf**

### CODE REVIEW

**Comment by incompl** [comment]
Hi, sorry I didn't see this before implementing the feature in a separate PR. This is now available as `isWaitingForAdBreak()`

**Comment by mysuf** [comment]
Nice. So I am closing this PR.

**Comment by incompl** [comment]
Sorry for the mix-up! I released this in 6.2.0.

**Comment by mysuf** [comment]
Yea. I saw that and it looks good. Maybe one minor bug: I visited it on mobile and some images overflows the page width. I guess that max-width: 100% on img will fix it.

**Comment by incompl** [comment]
Ah yes looks like the theme does that for image tags but not for SVGs. I'll fix it. Thanks!

**Pull request closed without merging**
